config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :klasses
    root to: "users#index"
  end
  devise_for :users
  resources :users
  # root, see: config/initializers/high_voltage.rb
end

app/models/klass.rb
# Using Klass (since Class is reserved)
class Klass < ActiveRecord::Base
  after_initialize :set_default_status, :if => :new_record?
  belongs_to :teacher, class_name: 'User'
  enum status: [:proposed, :accepted]
  monetize :materials_fee_cents, :allow_nil => true,
    :numericality => {
      :greater_than_or_equal_to => 0,
      :less_than_or_equal_to => 1000
    }
  validates :student_age_minimum, numericality: { only_integer: true, greater_than: 0, less_than: 149 }
  validates :student_age_maximum, numericality: { only_integer: true, greater_than: 1, less_than: 150 }
  validates :student_count_minimum, numericality: { only_integer: true, greater_than: 0 }
  validates :student_count_maximum, numericality: { only_integer: true, greater_than: 1 }

  # db defaults to 0,
  #  but Klass.new.status == nil (without this)
  def set_default_status
    self.status ||= :proposed
  end

end

app/models/teacher.rb
# read-only class, representing Teachers
#   will only provided necessary interface
class Teacher
  def self.all
    User.teachers
  end

  def self.count
    User.teachers.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :set_default_role, :if => :new_record?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
  :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin]
  has_many :klasses, foreign_key: 'teacher_id'

  scope :teachers, -> { joins(:klasses).where('teacher_id is not null') }

  # returns the appropriate identifier to help a human identify this user
  def moniker
    name || email
  end

  def set_default_role
    self.role ||= :user
  end
  private :set_default_role

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/klasses_controller.rb
module Admin
  class KlassesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Klass.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Klass.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :unless => :devise_controller?
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zurb_foundation_helper.rb
module ZurbFoundationHelper
  def top_bar_component(left_contents, right_contents=nil, title_contents=nil)
    content_tag('div', class: "top-bar") do

      left_tag = content_tag('div', class: "top-bar-left") do
        left_contents
      end
      nav_links = left_tag

      if right_contents.present?
        right_tag = content_tag('div', class: "top-bar-right") do
          right_contents
        end
        nav_links += right_tag
      end

      if title_contents.present?
        title_tag = content_tag('div', class: "top-bar-title") do
          title_contents
        end

        title_tag + content_tag('div') do
          nav_links
        end
      else
        nav_links
      end
    end
  end
end

app/views/admin/application/_sidebar.html.erb
<%#
# Sidebar

This partial is used to display the sidebar in Administrate.
By default, the sidebar contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<ul class="sidebar__list">
  <!-- CUSTOM: Add home link -->
  <li><%= link_to("Home", root_url, class: "sidebar__link") %></li>

  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <li>
      <%= link_to(
        display_resource_name(resource),
        [namespace, resource],
        class: "sidebar__link sidebar__link--#{nav_link_state(resource)}"
      ) %>
    </li>
  <% end %>
</ul>

app/views/admin/klasses/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label cell-label--<%= attr_type.html_class %>
          cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
            <%= attr_name.to_s.titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <!-- CUSTOM: pass resource as locals -->
            <%= render_field attribute, resource: resource %>

          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/klasses/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="Search"
      value="<%= search_term %>"
      aria-label="Search"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/fields/enum_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<%= f.select(
  field.attribute,
  options_for_select(
    f.object.class.public_send(field.attribute.to_s.pluralize) # method to list enum options
      .map { |k, v| [k.humanize, k] },
      f.object.public_send(field.attribute.to_s)),
  include_blank: false) %>

app/views/fields/enum_field/_index.html.erb
<!-- List all status, indicate current -->
<% statuses = resource.class.public_send(field.attribute.to_s.pluralize) # method to list enum options %>
<% statuses.each do |status_key, status_value| %>
  <% field.enum_iteratee = status_key %>
  <%= button_to field.caption,
    admin_klass_path(resource, {klass: {status: status_key.underscore}}),
    { method: :patch, class: field.css_classes } %>
<% end %>

app/views/fields/enum_field/_show.html.erb
<%= field.to_s %>

app/views/layouts/_nav_links.html.haml
-# add navigation links to this file
%ul.menu
  %li= link_to 'Home', root_path
  -# %li= link_to 'Class Proposals', klasses_path(status: :proposed)

app/views/layouts/_nav_links_for_auth.html.haml
%ul.menu.auth
  - if user_signed_in? && current_user.admin?
    %li= link_to 'Admin', '/admin'
    %li= link_to 'Users', users_path
    %li= "|" #divider

  - if user_signed_in?
    %li= link_to 'Edit account', edit_user_registration_path
    %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
  - else
    %li= link_to 'Sign in', new_user_session_path
    %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/admin/application.html.erb
<%#
# Application Layout

This view template is used as the layout
for every page that Administrate generates.

By default, it renders:
- Sidebar for navigation
- Content for a search bar
  (if provided by a `content_for` block in a nested page)
- Flashes
- Links to stylesheets and Javascripts
%>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= content_for(:title) %> | <%= Rails.application.class.parent_name.titlecase %></title>
  <!-- CUSTOM: stylesheet -->
  <%= stylesheet_link_tag "administrate/customizations", media: "all" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="app-container">

    <div class="sidebar">
      <%= render "sidebar" -%>
    </div>

    <main class="main-content" role="main">
      <%= content_for(:search) %>
      <%= render "flashes" -%>
      <%= yield %>
    </main>

  </div>

  <%= render "javascript" %>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    -# %meta{ :charset => "utf-8" } # foundation 6
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Passport Scheduler"

    -# = stylesheet_link_tag "application" # foundation 6
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true # rails
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    %header
      = top_bar_component(render('layouts/nav_links'), render('layouts/nav_links_for_auth'))
      - flash.each do |key, msg|
        = content_tag :div, msg, :id => key

    = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/welcome.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>